import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
      <Html>
        <Head>
          <meta name='description' content='Generated by create next app'/>
          <link rel='icon' href='/favicon.ico'/>
          <link rel='stylesheet'
                href='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/default.min.css'/>
          <link rel='preconnect' href='https://fonts.googleapis.com'/>
          <link rel='preconnect' href='https://fonts.gstatic.com'/>
          <link href='https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;700&display=swap'
                rel='stylesheet'/>
        </Head>
        <body>
        <Main/>
        <NextScript/>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js' defer/>
        <script>hljs.highlightAll();</script>
        </body>
      </Html>
  );
}